### ISSUE TITLE
time format

### ISSUE THREAD

**Issue by nitneuq33000** [MarcinusX/NumberPicker#30]
hello, I tried to make a number picker with one column for hour and an other for minutes.  I don't see how I can make a maxlimite to the decimal. currently decimal is 0 to 99, I want 0 to 60.  

thank you

**Comment by MarcinusX** [comment]
Hi man, I am not sure if it would be easily doable and I don't want to add a lot of complexity to this package since I think it is complex already.
If you have an idea on how to easily do this, feel free to create pull request but in my opinion the easiest solution would be to fork the repo and modify it for your own purpose.

**Comment by rickspencer3** [comment]
@nitneuq33000 I think Flutter comes with a Time chooser. 

If you want to use this package, could you not make a stateful widget with a row that has two NumberPickers with a ":" in between?

**Comment by MarcinusX** [comment]
Yeah, it seems like a much easier solution rather than changing the package itself.
Closing for now. Feel free to reopen if it won't work
